name: dotnet package

on:
  push:
    tags: [v*.*]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    defaults:
      run:
        working-directory: ./FsGrpc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -p:FSGRPC_VERSION=$($env:GITHUB_REF -replace "refs/tags/") --no-restore --no-build --configuration Release
      - name: Zip
        run: (cd bin/Release/net6.0/publish && zip -r ../FsGrpc.zip .)
      - name: Package
        run: dotnet pack -p:FSGRPC_VERSION=$($env:GITHUB_REF -replace "refs/tags/") --no-restore --no-build --configuration Release
      - name: Nuget Push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push bin/Release/FsGrpc.$($env:GITHUB_REF -replace "refs/tags/").nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
      - name: GitHubRelease
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./FsGrpc/bin/Release/FsGrpc.$($env:GITHUB_REF -replace "refs/tags/").nupkg
